#!/bin/bash

pkg update && pkg upgrade

pkg install php phpmyadmin mariadb

mv ~/termuxphp/config.inc.php $PREFIX/share/phpmyadmin/config.inc.php

mkdir -p $PREFIX/etc/php

echo 'error_reporting = 0' >> $PREFIX/etc/php/php.ini

mv ~/termuxphp/start.sh ~/

chmod +x ~/start.sh

rm -rf ~/termuxphp

echo 'installation done'
